### ISSUE TITLE
how to get ljloggedin cookie?

### ISSUE THREAD

**Issue by orleanz** [agentcooper/node-livejournal#3]
Hi,

I have a question - a sessiongenerate (  http://www.livejournal.com/doc/server/ljp.csp.xml-rpc.sessiongenerate.html ) returns only 1 cookie, namely ljsession. 

Example

LiveJournal.RPC.sessiongenerate({  mode: 'sessiongenerate',  auth_method: 'clear',  username: 'orleanz',  password: '*****'}, function(err, value) { console.log(value); });

Response:
{ ljsession: 'v2:u868......' }

It is an old name of this cookie, actuall name is ljmastersession. 

Quote from Brad Fitzpatrick's post 

http://lj-dev.livejournal.com/706840.html
" 
My bad. So, I did update generatesession to give you the new-format cookie, but you're supposed to send it as "ljmastersession" now, even though the protocol gives it back to you as ljsession.
"

So far so good. But to be able to use LJ by scripts, you need TWO cookies, ljmastersession and ljloggedin, which is described in http://www.livejournal.com/doc/server/ljp.int.cookie_scheme.html

Tested it in browser by manually deleting ljloggedin cookie and leaving ljmastersession only - logins does not work in this case.

So, how can I get this ljloggedin cookie programmatically?

Would be great to add this functionality to your tool, then all complexities of login would be masked from end-user!

**Comment by agentcooper** [comment]
Hey. I actually never used cookie scheme myself. I only have some experience with OAuth login - which is currently available only by request from LJ team, there is an example of OAuth scheme here http://ljreader.com

But isn't login/password scheme good enough for scripts? Although, I sure that asking a password in 3rd party app is not a good idea.

**Comment by orleanz** [comment]
Well, all I need is to find a way to get Social capital value for arbitrary user. Unfortunately, Livejournal is not showing Social Capital value on user's profile if you are not logged in (with some exceptions. for example, for Artemy Lebedev, it does show Social capital on profile page even if you are not logged in. But for avva, you do need to be logged in to see HIS social capital.) 

So my idea was that I will use my own login on the server to get users' social capital values.

**Comment by agentcooper** [comment]
So you would still scrape the html for the value? In this case you can POST username/password to
http://www.livejournal.com/login.bml?returnto={journal_profile_url} and use something like https://github.com/cheeriojs/cheerio to get the social capital value

**Comment by orleanz** [comment]
Hi, 

just wanted to show you the web version of my LJ friends / social capital tool. This tool is called Frendoskop and its gets FOF-based friend suggestions, as well as social-capital-based friend sorting.

http://lentascope.net/frendoskop

The tool is hosted at my other, bigger project, Lentascope, that allows reading ancien LJ friend feeds:

http://lentascope.net

Since you are so much involved into LJ dev (yes, I know, in the past, but anyway) - ANY your comment or opinion would be very welcome.

Regards, Dmitri
